# Generated by Django 3.2.14 on 2022-07-29 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pro_name',
        ),
    ]
