# Generated by Django 3.2.14 on 2022-08-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_brands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectgallery',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
